# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 06:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181221_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 6, 23, 50, 299674, tzinfo=utc)),
        ),
    ]
